services:
  postgres:
    image: docker.io/library/postgres:13.6-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_DEV_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_DEV_PASSWORD}

  elasticsearch:
    healthcheck:
      test: ['CMD', 'curl', '-f', '127.0.0.1:9200']
    image: docker.io/library/elasticsearch:7.17.26
    environment:
      http.host: 0.0.0.0
      transport.host: 0.0.0.0
      ES_JAVA_OPTS: -Xms2g -Xmx2g
      discovery.type: single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 4g

  kibana:
    depends_on:
      - elasticsearch
    image: docker.io/library/kibana:7.17.0

  logstash:
    env_file:
      - .env
    depends_on:
      - schema
    build: script/search_indexing
    tmpfs:
      - /usr/share/logstash/data
    environment:
      LS_JAVA_OPTS: -Xmx2g -Xms2g

  redis:
    image: docker.io/library/redis:7.2
    command: redis-server
    volumes:
      - redis:/data

  schema:
    build: .
    command: [rake, db:migrate, 'comfy:cms_seeds:import[lumen_cms,lumen_cms]', db:seed]
    depends_on:
      elasticsearch:
        condition: service_healthy
      postgres:
        condition: service_started
    env_file:
      - .env

  website:
    depends_on:
      schema:
        condition: service_completed_successfully
    build: .
    healthcheck:
      test: ['CMD', 'wget', '-q', '--spider', '127.0.0.1:3000']
    ports:
      - 3000:3000
    volumes:
      - .:/srv
    env_file:
      - .env

  jobs:
    depends_on:
      website:
        condition: service_healthy
    build: .
    volumes:
      - .:/srv
    env_file:
      - .env
    command: bundle exec sidekiq

volumes:
  postgres:
  esdata:
  redis:
