services:
  postgres:
    image: docker.io/library/postgres:13.6-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_DEV_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_DEV_PASSWORD}

  website:
    depends_on:
      - postgres
    build: .
    ports:
      - 8282:3000
    volumes:
      - '.:/app'
      - docker_website_bash_history:/home/lumen/hist
    env_file:
      - .env
    environment:
      HISTFILE: /home/lumen/hist/.bash_history

  elasticsearch:
    image: docker.io/library/elasticsearch:7.17.26
    environment:
      http.host: 0.0.0.0
      transport.host: 0.0.0.0
      ES_JAVA_OPTS: -Xms2g -Xmx2g
      discovery.type: single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 4g

  kibana:
    depends_on:
      - elasticsearch
    image: docker.io/library/kibana:7.17.0

  logstash:
    env_file:
      - .env
    depends_on:
      - elasticsearch
      - postgres
    build:
      context: .
      dockerfile: Dockerfile-logstash
    command: logstash --path.settings /app/script/search_indexing/
    volumes:
      - '.:/app:ro'
    tmpfs:
      - /user/share/logstash/data
    environment:
      LS_JAVA_OPTS: -Xmx2g -Xms2g

  redis:
    image: docker.io/library/redis:7.2
    command: redis-server
    volumes:
      - redis:/data

volumes:
  postgres:
  esdata:
  logstash:
  docker_website_bash_history:
  redis:
